name: G1TRACKING

defaults:
  # see https://hydra.cc/docs/advanced/overriding_packages/
  - /task/G1/G1
  - _self_

robot: 
  name: g1_col_full_self

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling: 
    .*elbow_joint: 1.0
    .*shoulder.*: 1.0
    .*wrist.*: 1.0
    .*hip_roll.*: 0.5
    .*hip_yaw.*: 0.5
    .*hip_pitch.*: 0.5
    .*knee.*: 0.5
    .*waist.*: 0.5
    .*ankle.*: 0.5
  max_delay: 4
  alpha: [0.9, 0.9]
  alpha_wide: [0.8, 1.0]
  alpha_jit_scale: 0.025
  boot_protect: True

flags: []
command:
  _target_: active_adaptation.envs.mdp.commands.motion_tracking.MotionTrackingCommand
  student_train: True
  keypoint_map: {}
  keypoint_patterns: ["head_mimic", ".*_hand_mimic", ".*wrist_roll_link.*", ".*shoulder_yaw_link", ".*knee.*", ".*ankle_roll_link"]
  lower_keypoint_patterns: [".*knee.*", ".*ankle_roll_link"]
  upper_keypoint_patterns: ["head_mimic", ".*_hand_mimic", ".*wrist_roll_link.*", ".*shoulder_yaw_link"]
  feet_patterns: ["left_ankle_roll_link", "right_ankle_roll_link"]
  ignore_joint_patterns: []
  joint_patterns: [".*hip.*", ".*knee.*", ".*shoulder.*", ".*wrist.*", ".*waist.*"]
  dataset:
    mem_paths:
      - lafan_all
      # - amass_all
    path_weights:
      - 1.0
      # - 0.6
  dataset_extra_keys: []
  future_steps: [0, 2, 4, 8, 16]
  cum_root_pos_scale: 1.5
  cum_keypoint_scale: 0.25
  cum_orientation_scale: 0.7
  body_z_terminate_thres: 0.25
  body_z_terminate_patterns: ["pelvis", ".*_hand_mimic", ".*ankle_roll.*"]
  reinit_prob: 0.8
  reinit_min_steps: 25
  reinit_max_steps: 75
  gravity_terminate_thres: 0.5
  boot_indicator_max: 25
  init_noise:
    root_pos: 0.03
    root_ori: 0.1
    root_lin_vel: 0.1
    root_ang_vel: 0.1
    joint_pos: 0.1
    joint_vel: 0.1
  reward_sigma:
    root_pos: [0.3]
    root_vel: [1.0]
    root_rot: [0.4]
    root_ang_vel: [3.0]
    
    keypoint: [0.3] # product
    keypoint_vel: [1.0] # product
    keypoint_rot: [0.4] # product
    keypoint_angvel: [3.0] # product
    lower_keypoint: [0.2] # product
    upper_keypoint: [0.3] # product

    joint_pos: [0.5] # product
    joint_vel: [3.0] # product

observation:
  policy:
    boot_indicator_state: {}
    command: {}
    target_root_z_obs: {}
    target_joint_pos_obs: {}
    target_projected_gravity_b: {}

    root_ang_vel_history:      {history_steps: [0], noise_std: 0.05}
    projected_gravity_history: {history_steps: [0], noise_std: 0.01}

    joint_pos_history:         {history_steps: [0, 1, 2, 3, 4, 8], noise_std: 0.01}
    prev_actions:   {steps: 3}
  priv:
    # tracking
    target_pos_b_obs: {}
    target_linvel_b_obs: {}
    relative_quat_obs: {}
    # feet & support
    body_height:      {body_names: ["pelvis", "torso_link", ".*ankle_roll_link"]}
    contact_forces:   {body_names: [.*ankle_roll_link]}
    # root
    root_linvel_b:    {ema: 0.2}
    root_ang_vel_history:      {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}
    projected_gravity_history: {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}
    # joint
    joint_pos_history:         {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}
    # bodies
    current_keypoint_b: {}
    current_keypoint_vel_b: {}
    target_keypoints_diff_b_obs: {}
    # action&torque
    applied_action:   {}
    applied_torque:   {}
  priv_critic:
    cum_error:        {}

reward:
  _student_train_: False
  tracking:
    root_pos_tracking:     {weight: 0.5}
    root_rot_tracking:  {weight: 0.5}
    root_vel_tracking:     {weight: 1.0}
    root_ang_vel_tracking: {weight: 1.0}

    keypoint_tracking:     {weight: 1.0}
    keypoint_vel_tracking: {weight: 1.0}
    keypoint_rot_tracking: {weight: 1.0}
    keypoint_angvel_tracking: {weight: 1.0}
    lower_keypoint_tracking: {weight: 0.5}
    upper_keypoint_tracking: {weight: 0.5}

    joint_pos_tracking:    {weight: 1.0}
    joint_vel_tracking:    {weight: 0.5}
  loco:
    survival:           {weight: 4.0, enabled: true}
    impact_force_l2:    {weight: 4.0, enabled: true, body_names: .*ankle_roll_link}
    feet_slip:          {weight: 2.0, enabled: true, body_names: .*ankle_roll_link}
    joint_vel_l2:       {weight: 5.0e-4, enabled: true, joint_names: .*}
    action_rate_l2:     {weight: 0.1, enabled: true}
    feet_air_time_ref:  {weight: 10.0, enabled: true, body_names: [left_ankle_roll_link, right_ankle_roll_link], thres: 0.8}
    joint_pos_limits:   {weight: 1.0, joint_names: ".*", soft_factor: 0.9, enabled: true}
    joint_torque_limits: {weight: 0.01, joint_names: ".*", soft_factor: 0.75, enabled: true}
    feet_contact_count: {weight: 1.0, enabled: false, body_names: .*ankle_roll_link, }

randomization:
  perturb_body_com:
    body_names: ["pelvis", "torso_link"]
    com_range: [-0.02, 0.02]
  perturb_body_materials:
    body_names: ".*ankle_roll_link"
    static_friction_range: [0.3, 1.6]
    dynamic_friction_frac_range: [0.75, 1.0]
    restitution_range: [0.0, 0.2]
  motor_params_implicit:
    stiffness_range:
      .*: [0.8, 1.2]
    damping_range:
      .*: [0.8, 1.2]
    armature_range:
      .*: [0.75, 1.25]
  random_joint_offset: 
    .*: [-0.01, 0.01]

termination:
  # cum_error: {thres: 1.0, min_steps: 50}
  body_z_termination: {}
  gravity_dir_termination: {}
