# @package _global_

defaults:
  - override /algo: ppo_train

algo:
  init_noise_scale: 1.0
  init_noise_scale_overrides:
    ".*waist.*": 1.5
    ".*wrist.*": 1.0
    ".*shoulder.*": 1.2
    ".*elbow.*": 1.2
    ".*knee.*": 1.5
    ".*hip.*": 1.5
    ".*ankle.*": 1.0
  load_noise_scale: null

task:
  command:
    student_train: False
  reward:
    _student_train_: false
    loco:
      _scale_factor_: [0.0, 1.0, 0.5, 1.0]
      joint_acc_l2:       {weight: 2.0e-8, enabled: true, joint_names: .*}

total_frames: 8000_000_000
